# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4bea3f8b3380e04af7889798a7737a8e960131caf5986d4d064eb1e891959791ab3af2106125d528bf41158fa75e45d67eba0693d01f501bc5e37d9e6ce93c2

test:
  secret_key_base: 8a587ca9f63cd71460f67ed2e2b747c452b81ac7749b91f4b8c1d088b5356d6aed69345b213f8e788943e24d6e08cb92da782daea70169d1c175520bed3aec71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
